name: drivolution
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  archive: ^3.6.1
  audioplayers: ^6.1.0
  cached_network_image: ^3.2.3
  connectivity_plus: ^6.1.0
  cupertino_icons: ^1.0.2
  dio: ^5.2.1+1
  dropdown_button2: ^2.0.0
  email_validator: ^3.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.2.1
  flutter_secure_storage: ^9.2.2
  flutter_styled_toast: ^2.2.1
  font_awesome_flutter: ^10.5.0
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.3.1
  google_nav_bar: ^5.0.6
  googleapis_auth: ^1.5.0
  http: ^1.0.0
  iconly: ^1.0.1
  image: ^4.0.17
  image_picker: ^1.1.2
  image_to_byte: ^1.0.0
  intl: ^0.19.0
  jwt_decoder: ^2.0.1
  liquid_pull_to_refresh: ^3.0.1
  logging: ^1.3.0
  lottie: ^3.1.3
  numberpicker: ^2.1.2
  page_transition: ^2.0.9
  path_provider: ^2.1.5
  photo_view: ^0.15.0
  readmore: ^3.0.0
  shimmer: ^3.0.0
  simple_gradient_text: ^1.2.4
  smooth_page_indicator: ^1.0.1
  syncfusion_flutter_datepicker: ^27.2.2
  synchronized: ^3.3.0+3
  url_launcher: ^6.1.11
  win32: ^5.8.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/logo/logo.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/img/logo/logo2.png"

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/lottie/
    - assets/img/cars/
    - assets/img/logo/
    - assets/icons/
    - .env
    - assets/sounds/
    - .env

  fonts:
    - family: Karla
      fonts:
        - asset: assets/fonts/karla/Karla-Regular.ttf
          weight: 400
        - asset: assets/fonts/karla/Karla-Medium.ttf
          weight: 500
        - asset: assets/fonts/karla/Karla-Bold.ttf
          weight: 700

    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500

    - family: Amiri
      fonts:
        - asset: assets/fonts/amiri/Amiri-Regular.ttf
          weight: 400
        - asset: assets/fonts/amiri/Amiri-Bold.ttf
          weight: 700
