// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJNNlMgriLlcvRP2Llig-sUYtn3to_Ad4',
    appId: '1:51613972745:web:b113c72517e93f2341bbd8',
    messagingSenderId: '51613972745',
    projectId: 'drivolution',
    authDomain: 'drivolution.firebaseapp.com',
    storageBucket: 'drivolution.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGPW7O3RyBRqE-hE5AVuNzkxLkeo0Om7E',
    appId: '1:51613972745:android:be77423eef5afe6b41bbd8',
    messagingSenderId: '51613972745',
    projectId: 'drivolution',
    storageBucket: 'drivolution.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4Eo-KVn6AvtGwClH7MCSHouJG1EBqSH0',
    appId: '1:51613972745:ios:850eea8fd0b059e741bbd8',
    messagingSenderId: '51613972745',
    projectId: 'drivolution',
    storageBucket: 'drivolution.appspot.com',
    iosClientId: '51613972745-nj5rcgup0qsekp7vq43thrcvvdg68qig.apps.googleusercontent.com',
    iosBundleId: 'com.example.drivolution',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4Eo-KVn6AvtGwClH7MCSHouJG1EBqSH0',
    appId: '1:51613972745:ios:4c3a9fc7a3ff5d6941bbd8',
    messagingSenderId: '51613972745',
    projectId: 'drivolution',
    storageBucket: 'drivolution.appspot.com',
    iosClientId: '51613972745-a51ug4etfhdsehrbqifj4negjcs6hn1b.apps.googleusercontent.com',
    iosBundleId: 'com.example.drivolution.RunnerTests',
  );
}
